# Generated by Django 5.2.6 on 2025-09-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Location name (e.g. 'Downtown Salon')", max_length=100)),
                ('address', models.TextField(help_text='Full address of this location')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('monday_hours', models.CharField(blank=True, default='9:00 AM - 6:00 PM', max_length=50)),
                ('tuesday_hours', models.CharField(blank=True, default='9:00 AM - 6:00 PM', max_length=50)),
                ('wednesday_hours', models.CharField(blank=True, default='9:00 AM - 6:00 PM', max_length=50)),
                ('thursday_hours', models.CharField(blank=True, default='9:00 AM - 6:00 PM', max_length=50)),
                ('friday_hours', models.CharField(blank=True, default='9:00 AM - 6:00 PM', max_length=50)),
                ('saturday_hours', models.CharField(blank=True, default='10:00 AM - 4:00 PM', max_length=50)),
                ('sunday_hours', models.CharField(blank=True, default='Closed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Employee email (optional)', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Employee phone (optional)', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Brief bio or specialties (optional)')),
                ('hire_date', models.DateField(blank=True, help_text='Date hired (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this employee currently working?')),
                ('monday_schedule', models.CharField(blank=True, help_text="e.g. '9:00 AM - 5:00 PM' or 'Off'", max_length=50)),
                ('tuesday_schedule', models.CharField(blank=True, help_text="e.g. '9:00 AM - 5:00 PM' or 'Off'", max_length=50)),
                ('wednesday_schedule', models.CharField(blank=True, help_text="e.g. '9:00 AM - 5:00 PM' or 'Off'", max_length=50)),
                ('thursday_schedule', models.CharField(blank=True, help_text="e.g. '9:00 AM - 5:00 PM' or 'Off'", max_length=50)),
                ('friday_schedule', models.CharField(blank=True, help_text="e.g. '9:00 AM - 5:00 PM' or 'Off'", max_length=50)),
                ('saturday_schedule', models.CharField(blank=True, help_text="e.g. '10:00 AM - 4:00 PM' or 'Off'", max_length=50)),
                ('sunday_schedule', models.CharField(blank=True, help_text="e.g. '10:00 AM - 4:00 PM' or 'Off'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='Primary work location', on_delete=django.db.models.deletion.CASCADE, to='booking.location')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Service name (e.g. 'Haircut & Style')", max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in dollars (e.g. 45.00)', max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(help_text='How long does this service take? (in minutes)')),
                ('category', models.CharField(choices=[('hair', 'Hair Services'), ('nails', 'Nail Services'), ('skincare', 'Skincare & Facials'), ('massage', 'Massage & Spa'), ('makeup', 'Makeup Services'), ('other', 'Other Services')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this service from booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locations', models.ManyToManyField(help_text='Which locations offer this service?', to='booking.location')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(help_text="Customer's first name", max_length=50)),
                ('customer_last_name', models.CharField(help_text="Customer's last name", max_length=50)),
                ('customer_email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('customer_phone', models.CharField(help_text="Customer's phone number", max_length=20)),
                ('preferred_date', models.DateField(help_text='Preferred appointment date')),
                ('preferred_time', models.TimeField(help_text='Preferred appointment time')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests from customer')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes for staff (not visible to customer)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_employee', models.ForeignKey(blank=True, help_text='Preferred employee (optional - leave blank for any available)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.employee')),
                ('location', models.ForeignKey(help_text='Which location?', on_delete=django.db.models.deletion.CASCADE, to='booking.location')),
                ('service', models.ForeignKey(help_text='Which service?', on_delete=django.db.models.deletion.CASCADE, to='booking.service')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(help_text='Services this employee can perform', to='booking.service'),
        ),
    ]
