# Generated by Django 5.2.6 on 2025-09-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='friday_schedule',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 7:00 PM', '11:00 AM - 7:00 PM'), ('12:00 PM - 8:00 PM', '12:00 PM - 8:00 PM'), ('9:00 AM - 3:00 PM', '9:00 AM - 3:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM')], default='9:00 AM - 5:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monday_schedule',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 7:00 PM', '11:00 AM - 7:00 PM'), ('12:00 PM - 8:00 PM', '12:00 PM - 8:00 PM'), ('9:00 AM - 3:00 PM', '9:00 AM - 3:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM')], default='9:00 AM - 5:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='saturday_schedule',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 7:00 PM', '11:00 AM - 7:00 PM'), ('12:00 PM - 8:00 PM', '12:00 PM - 8:00 PM'), ('9:00 AM - 3:00 PM', '9:00 AM - 3:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM')], default='Off', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sunday_schedule',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 7:00 PM', '11:00 AM - 7:00 PM'), ('12:00 PM - 8:00 PM', '12:00 PM - 8:00 PM'), ('9:00 AM - 3:00 PM', '9:00 AM - 3:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM')], default='Off', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thursday_schedule',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 7:00 PM', '11:00 AM - 7:00 PM'), ('12:00 PM - 8:00 PM', '12:00 PM - 8:00 PM'), ('9:00 AM - 3:00 PM', '9:00 AM - 3:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM')], default='9:00 AM - 5:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tuesday_schedule',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 7:00 PM', '11:00 AM - 7:00 PM'), ('12:00 PM - 8:00 PM', '12:00 PM - 8:00 PM'), ('9:00 AM - 3:00 PM', '9:00 AM - 3:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM')], default='9:00 AM - 5:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wednesday_schedule',
            field=models.CharField(blank=True, choices=[('Off', 'Off'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 7:00 PM', '11:00 AM - 7:00 PM'), ('12:00 PM - 8:00 PM', '12:00 PM - 8:00 PM'), ('9:00 AM - 3:00 PM', '9:00 AM - 3:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM')], default='9:00 AM - 5:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='friday_hours',
            field=models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='9:00 AM - 6:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='monday_hours',
            field=models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='9:00 AM - 6:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='saturday_hours',
            field=models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='10:00 AM - 4:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='sunday_hours',
            field=models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='Closed', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='thursday_hours',
            field=models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='9:00 AM - 6:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='tuesday_hours',
            field=models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='9:00 AM - 6:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='wednesday_hours',
            field=models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='9:00 AM - 6:00 PM', max_length=50),
        ),
    ]
