# Generated by Django 5.2.6 on 2025-09-11 08:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_add_hour_choices'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, help_text='Introduction text shown above the booking form')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, default="<p>Thank you for your booking request! We'll contact you within 24 hours to confirm your appointment.</p>", help_text='Message shown after successful form submission')),
            ],
            options={
                'verbose_name': 'Booking Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
