# Generated by Django 5.2.6 on 2025-09-11 09:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpage',
            name='intro_text',
        ),
        migrations.AddField(
            model_name='bookingpage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 6), ('booking_form', 9), ('services', 17), ('features', 23), ('cta', 26), ('text', 29), ('gallery', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome to Beauty Salon', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'default': 'Transform your beauty with premium treatments'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Book Now', 'max_length': 50}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Services', 'max_length': 50}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('hero_image', 2), ('background_image', 2), ('primary_button_text', 3), ('primary_button_url', 4), ('secondary_button_text', 5), ('secondary_button_url', 4)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Appointment', 'max_length': 200}), 8: ('wagtail.blocks.TextBlock', (), {'default': "Fill out the form below and we'll contact you within 24 hours"}), 9: ('wagtail.blocks.StructBlock', [[('title', 7), ('subtitle', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'Our Services', 'max_length': 200}), 11: ('wagtail.blocks.TextBlock', (), {'default': 'Professional beauty treatments'}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 14: ('wagtail.blocks.TextBlock', (), {}), 15: ('wagtail.blocks.StructBlock', [[('image', 12), ('title', 13), ('description', 14), ('link_url', 4)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('title', 10), ('subtitle', 11), ('services', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Why Choose Us', 'max_length': 200}), 19: ('wagtail.blocks.TextBlock', (), {'default': 'Quality service you can trust'}), 20: ('wagtail.blocks.StructBlock', [[('image', 12), ('title', 13), ('description', 14)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('light', 'Light Gray'), ('primary', 'Brand Color')]}), 23: ('wagtail.blocks.StructBlock', [[('title', 18), ('subtitle', 19), ('features', 21), ('background_style', 22)]], {}), 24: ('wagtail.blocks.TextBlock', (), {'default': 'Ready to look your best?'}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Contact', 'max_length': 50}), 26: ('wagtail.blocks.StructBlock', [[('title', 7), ('subtitle', 24), ('primary_button_text', 3), ('primary_button_url', 4), ('secondary_button_text', 25), ('secondary_button_url', 4), ('background_style', 22)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 28: ('wagtail.blocks.RichTextBlock', (), {}), 29: ('wagtail.blocks.StructBlock', [[('title', 27), ('content', 28), ('background_style', 22)]], {}), 30: ('wagtail.blocks.ListBlock', (12,), {}), 31: ('wagtail.blocks.StructBlock', [[('title', 27), ('images', 30)]], {})}),
        ),
    ]
