# Generated by Django 5.2.6 on 2025-09-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_bookingpage_intro_text_bookingpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='preferred_employee',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='preferred_employee_notes',
            field=models.CharField(blank=True, help_text='Optional: Any specific employee preferences or notes', max_length=200),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
