# Generated by Django 5.2.6 on 2025-09-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_formsubmission_preferred_employee_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='preferred_employee_notes',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Available for bookings?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_page', models.ForeignKey(blank=True, help_text='Connected employee page (auto-set)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page')),
                ('location', models.ForeignKey(help_text='Primary work location', on_delete=django.db.models.deletion.CASCADE, to='booking.location')),
                ('services', models.ManyToManyField(help_text='Services this employee can perform', to='booking.service')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='preferred_employee',
            field=models.ForeignKey(blank=True, help_text='Preferred employee (optional - leave blank for any available)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.employee'),
        ),
    ]
