# Generated by Django 5.2.6 on 2025-09-12 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_bookingpage_content'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='bookingpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero image (overlays background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='bookingpage',
            name='hero_primary_button_text',
            field=models.CharField(blank=True, default='Book Now', help_text='Primary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingpage',
            name='hero_primary_button_url',
            field=models.URLField(blank=True, help_text='Primary button URL'),
        ),
        migrations.AddField(
            model_name='bookingpage',
            name='hero_secondary_button_text',
            field=models.CharField(blank=True, default='Services', help_text='Secondary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingpage',
            name='hero_secondary_button_url',
            field=models.URLField(blank=True, help_text='Secondary button URL'),
        ),
        migrations.AddField(
            model_name='bookingpage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Transform your beauty with premium treatments', help_text='Subtitle text below the main headline'),
        ),
        migrations.AddField(
            model_name='bookingpage',
            name='hero_title',
            field=models.CharField(blank=True, default='Welcome to Beauty Salon', help_text='Main hero headline', max_length=200),
        ),
        migrations.AddField(
            model_name='bookingpage',
            name='show_hero',
            field=models.BooleanField(default=True, help_text='Show hero section at the top of this page'),
        ),
    ]
