# Generated by Django 5.2.6 on 2025-09-12 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookingpage_hero_background_image_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_page',
            field=models.ForeignKey(blank=True, help_text='Connected location page (auto-set)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page'),
        ),
    ]
