# Generated by Django 5.2.6 on 2025-09-12 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_location_location_page'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_page',
            field=models.ForeignKey(blank=True, help_text='Connected service page (auto-set)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Service description (auto-synced)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Service duration (auto-synced)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Available for bookings?'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Service name (auto-synced from service page)', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Service price (auto-synced)', max_digits=8),
        ),
    ]
