# Generated by Django 5.2.6 on 2025-09-15 11:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_service_service_page_alter_service_description_and_more'),
        ('home', '0012_remove_employeepage_work_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='preferred_employee',
            field=models.ForeignKey(blank=True, help_text='Preferred employee (optional - leave blank for any available)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_submissions', to='home.employeepage'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_page',
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='location',
            field=models.ForeignKey(help_text='Which location?', on_delete=django.db.models.deletion.CASCADE, related_name='booking_submissions', to='home.locationpage'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_page',
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='service',
            field=models.ForeignKey(help_text='Which service?', on_delete=django.db.models.deletion.CASCADE, related_name='booking_submissions', to='home.servicepage'),
        ),
        migrations.AlterModelOptions(
            name='bookingpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Booking Submission', 'verbose_name_plural': 'Booking Submissions'},
        ),
        migrations.AlterField(
            model_name='bookingpage',
            name='content',
            field=wagtail.fields.StreamField([('booking_form', 2), ('services', 11), ('features', 17), ('cta', 21), ('text', 24), ('gallery', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Appointment', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'default': "Fill out the form below and we'll contact you to confirm your booking."}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Our Services', 'max_length': 200}), 4: ('wagtail.blocks.TextBlock', (), {'default': 'Professional beauty treatments'}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.URLBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('title', 6), ('description', 7), ('link_url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 3), ('subtitle', 4), ('services', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Why Choose Us', 'max_length': 200}), 13: ('wagtail.blocks.TextBlock', (), {'default': 'Quality service you can trust'}), 14: ('wagtail.blocks.StructBlock', [[('image', 5), ('title', 6), ('description', 7)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('light', 'Light Gray'), ('primary', 'Brand Color')]}), 17: ('wagtail.blocks.StructBlock', [[('title', 12), ('subtitle', 13), ('features', 15), ('background_style', 16)]], {}), 18: ('wagtail.blocks.TextBlock', (), {'default': 'Ready to look your best?'}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Book Now', 'max_length': 50}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Contact', 'max_length': 50}), 21: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 18), ('primary_button_text', 19), ('primary_button_url', 8), ('secondary_button_text', 20), ('secondary_button_url', 8), ('background_style', 16)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 23: ('wagtail.blocks.RichTextBlock', (), {}), 24: ('wagtail.blocks.StructBlock', [[('title', 22), ('content', 23), ('background_style', 16)]], {}), 25: ('wagtail.blocks.ListBlock', (5,), {}), 26: ('wagtail.blocks.StructBlock', [[('title', 22), ('images', 25)]], {})}),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
