# Generated by Django 5.2.6 on 2025-09-10 06:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_primary_text',
            field=models.CharField(default='Book Now', help_text='Primary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_primary_url',
            field=models.URLField(blank=True, help_text='Primary button URL (leave blank to use /book/)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_secondary_text',
            field=models.CharField(default='Contact Us', help_text='Secondary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_secondary_url',
            field=models.URLField(blank=True, help_text='Secondary button URL (leave blank to use /contact/)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_subtitle',
            field=models.TextField(default='Book your appointment today and discover your most beautiful self', help_text='Call to action subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(default='Ready to Transform?', help_text='Call to action title', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter an emoji for the feature', 'max_length': 10}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('icon_emoji', 0), ('title', 1), ('description', 2)]], {})}, help_text='Add features/benefits to display'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_subtitle',
            field=models.TextField(default="We're committed to making you look and feel your absolute best", help_text='Subtitle for the features section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_title',
            field=models.CharField(default='Why Choose Us?', help_text='Title for the features section', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero section background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(default='Experience luxury beauty treatments with our expert stylists and cutting-edge techniques', help_text='Subtitle text under the main headline'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Your Beauty Journey Starts Here', help_text='Main headline for the hero section', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter an emoji for the service (e.g., 💅)', 'max_length': 10}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link to service page', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('icon_emoji', 0), ('title', 1), ('description', 2), ('link_url', 3)]], {})}, help_text='Add services to display on the homepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle',
            field=models.TextField(default='Discover our range of beauty treatments designed to make you shine', help_text='Subtitle for the services section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(default='Our Premium Services', help_text='Title for the services section', max_length=200),
        ),
    ]
