# Generated by Django 5.2.6 on 2025-09-10 10:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cta_primary_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_primary_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_secondary_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_secondary_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='features',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='features_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='features_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 8), ('services_grid', 17), ('features_grid', 24), ('call_to_action', 29), ('text', 32), ('gallery', 36)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Your Beauty Journey Starts Here', 'help_text': 'Main headline for the hero section', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'default': 'Experience luxury beauty treatments with our expert stylists and cutting-edge techniques', 'help_text': 'Subtitle text under the main headline'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Hero section main image (appears on the right side)', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for the entire hero section (optional)', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Session', 'help_text': 'Primary button text', 'max_length': 50}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'Primary button URL', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Explore Services', 'help_text': 'Secondary button text', 'max_length': 50}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'Secondary button URL', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('hero_image', 2), ('background_image', 3), ('primary_button_text', 4), ('primary_button_url', 5), ('secondary_button_text', 6), ('secondary_button_url', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Our Premium Services', 'help_text': 'Title for the services section', 'max_length': 200}), 10: ('wagtail.blocks.TextBlock', (), {'default': 'Discover our range of beauty treatments designed to make you shine', 'help_text': 'Subtitle for the services section'}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image for this service'}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 13: ('wagtail.blocks.TextBlock', (), {}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link to service page', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('image', 11), ('title', 12), ('description', 13), ('link_url', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Add services to display'}), 17: ('wagtail.blocks.StructBlock', [[('title', 9), ('subtitle', 10), ('services', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Why Choose Us?', 'help_text': 'Title for the features section', 'max_length': 200}), 19: ('wagtail.blocks.TextBlock', (), {'default': "We're committed to making you look and feel your absolute best", 'help_text': 'Subtitle for the features section'}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload an image for this feature'}), 21: ('wagtail.blocks.StructBlock', [[('image', 20), ('title', 12), ('description', 13)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'help_text': 'Add features/benefits to display'}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White Background'), ('light', 'Light Gray Background'), ('primary', 'Brand Color Background')], 'help_text': 'Background style for this section'}), 24: ('wagtail.blocks.StructBlock', [[('title', 18), ('subtitle', 19), ('features', 22), ('background_style', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Ready to Transform?', 'help_text': 'Call to action title', 'max_length': 200}), 26: ('wagtail.blocks.TextBlock', (), {'default': 'Book your appointment today and discover your most beautiful self', 'help_text': 'Call to action subtitle'}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Book Now', 'help_text': 'Primary button text', 'max_length': 50}), 28: ('wagtail.blocks.CharBlock', (), {'default': 'Contact Us', 'help_text': 'Secondary button text', 'max_length': 50}), 29: ('wagtail.blocks.StructBlock', [[('title', 25), ('subtitle', 26), ('primary_button_text', 27), ('primary_button_url', 5), ('secondary_button_text', 28), ('secondary_button_url', 7), ('background_style', 23)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional section title', 'max_length': 200, 'required': False}), 31: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Rich text content'}), 32: ('wagtail.blocks.StructBlock', [[('title', 30), ('content', 31), ('background_style', 23)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional gallery title', 'max_length': 200, 'required': False}), 34: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 35: ('wagtail.blocks.ListBlock', (34,), {'help_text': 'Add images to the gallery'}), 36: ('wagtail.blocks.StructBlock', [[('title', 33), ('images', 35)]], {})}, help_text='Build your homepage using flexible content blocks'),
        ),
    ]
