# Generated by Django 5.2.6 on 2025-09-11 09:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_cta_primary_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 6), ('services', 14), ('features', 20), ('cta', 24), ('text', 27), ('gallery', 29)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome to Beauty Salon', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'default': 'Transform your beauty with premium treatments'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Book Now', 'max_length': 50}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Services', 'max_length': 50}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('hero_image', 2), ('background_image', 2), ('primary_button_text', 3), ('primary_button_url', 4), ('secondary_button_text', 5), ('secondary_button_url', 4)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Our Services', 'max_length': 200}), 8: ('wagtail.blocks.TextBlock', (), {'default': 'Professional beauty treatments'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 11: ('wagtail.blocks.TextBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('image', 9), ('title', 10), ('description', 11), ('link_url', 4)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('title', 7), ('subtitle', 8), ('services', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Why Choose Us', 'max_length': 200}), 16: ('wagtail.blocks.TextBlock', (), {'default': 'Quality service you can trust'}), 17: ('wagtail.blocks.StructBlock', [[('image', 9), ('title', 10), ('description', 11)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('light', 'Light Gray'), ('primary', 'Brand Color')]}), 20: ('wagtail.blocks.StructBlock', [[('title', 15), ('subtitle', 16), ('features', 18), ('background_style', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Appointment', 'max_length': 200}), 22: ('wagtail.blocks.TextBlock', (), {'default': 'Ready to look your best?'}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Contact', 'max_length': 50}), 24: ('wagtail.blocks.StructBlock', [[('title', 21), ('subtitle', 22), ('primary_button_text', 3), ('primary_button_url', 4), ('secondary_button_text', 23), ('secondary_button_url', 4), ('background_style', 19)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 26: ('wagtail.blocks.RichTextBlock', (), {}), 27: ('wagtail.blocks.StructBlock', [[('title', 25), ('content', 26), ('background_style', 19)]], {}), 28: ('wagtail.blocks.ListBlock', (9,), {}), 29: ('wagtail.blocks.StructBlock', [[('title', 25), ('images', 28)]], {})}),
        ),
    ]
