# Generated by Django 5.2.6 on 2025-09-12 09:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_formsubmission_preferred_employee_and_more'),
        ('home', '0006_alter_homepage_content'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the employees page')),
            ],
            options={
                'verbose_name': 'Employees Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EmployeePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('first_name', models.CharField(help_text="Employee's first name", max_length=100)),
                ('full_name', models.CharField(help_text="Employee's full display name", max_length=200)),
                ('email', models.EmailField(blank=True, help_text="Employee's email address", max_length=254)),
                ('job_title', models.CharField(help_text="Employee's job title/position", max_length=200)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text="Employee's bio, specialties, or description")),
                ('employee_image', models.ForeignKey(blank=True, help_text='Employee photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('location', models.ForeignKey(blank=True, help_text="Employee's primary work location", null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.location')),
            ],
            options={
                'verbose_name': 'Employee Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
