# Generated by Django 5.2.6 on 2025-09-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_employeespage_employeepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepage',
            name='last_name',
            field=models.CharField(default='Unknown', help_text="Employee's last name", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeepage',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full display name (auto-generated if empty)', max_length=200),
        ),
    ]
