# Generated by Django 5.2.6 on 2025-09-12 10:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_employeepage_last_name_alter_employeepage_full_name'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='employeepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero image (overlays background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='employeepage',
            name='hero_primary_button_text',
            field=models.CharField(blank=True, default='Book Now', help_text='Primary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='employeepage',
            name='hero_primary_button_url',
            field=models.URLField(blank=True, help_text='Primary button URL'),
        ),
        migrations.AddField(
            model_name='employeepage',
            name='hero_secondary_button_text',
            field=models.CharField(blank=True, default='Services', help_text='Secondary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='employeepage',
            name='hero_secondary_button_url',
            field=models.URLField(blank=True, help_text='Secondary button URL'),
        ),
        migrations.AddField(
            model_name='employeepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Transform your beauty with premium treatments', help_text='Subtitle text below the main headline'),
        ),
        migrations.AddField(
            model_name='employeepage',
            name='hero_title',
            field=models.CharField(blank=True, default='Welcome to Beauty Salon', help_text='Main hero headline', max_length=200),
        ),
        migrations.AddField(
            model_name='employeepage',
            name='show_hero',
            field=models.BooleanField(default=True, help_text='Show hero section at the top of this page'),
        ),
        migrations.AddField(
            model_name='employeespage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='employeespage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero image (overlays background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='employeespage',
            name='hero_primary_button_text',
            field=models.CharField(blank=True, default='Book Now', help_text='Primary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='employeespage',
            name='hero_primary_button_url',
            field=models.URLField(blank=True, help_text='Primary button URL'),
        ),
        migrations.AddField(
            model_name='employeespage',
            name='hero_secondary_button_text',
            field=models.CharField(blank=True, default='Services', help_text='Secondary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='employeespage',
            name='hero_secondary_button_url',
            field=models.URLField(blank=True, help_text='Secondary button URL'),
        ),
        migrations.AddField(
            model_name='employeespage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Transform your beauty with premium treatments', help_text='Subtitle text below the main headline'),
        ),
        migrations.AddField(
            model_name='employeespage',
            name='hero_title',
            field=models.CharField(blank=True, default='Welcome to Beauty Salon', help_text='Main hero headline', max_length=200),
        ),
        migrations.AddField(
            model_name='employeespage',
            name='show_hero',
            field=models.BooleanField(default=True, help_text='Show hero section at the top of this page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero image (overlays background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_text',
            field=models.CharField(blank=True, default='Book Now', help_text='Primary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_url',
            field=models.URLField(blank=True, help_text='Primary button URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_text',
            field=models.CharField(blank=True, default='Services', help_text='Secondary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_url',
            field=models.URLField(blank=True, help_text='Secondary button URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Transform your beauty with premium treatments', help_text='Subtitle text below the main headline'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='Welcome to Beauty Salon', help_text='Main hero headline', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_hero',
            field=models.BooleanField(default=True, help_text='Show hero section at the top of this page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('services', 8), ('features', 14), ('cta', 19), ('text', 22), ('gallery', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Our Services', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'default': 'Professional beauty treatments'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 3), ('description', 4), ('link_url', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('services', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Why Choose Us', 'max_length': 200}), 10: ('wagtail.blocks.TextBlock', (), {'default': 'Quality service you can trust'}), 11: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 3), ('description', 4)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('light', 'Light Gray'), ('primary', 'Brand Color')]}), 14: ('wagtail.blocks.StructBlock', [[('title', 9), ('subtitle', 10), ('features', 12), ('background_style', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Book Your Appointment', 'max_length': 200}), 16: ('wagtail.blocks.TextBlock', (), {'default': 'Ready to look your best?'}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Book Now', 'max_length': 50}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Contact', 'max_length': 50}), 19: ('wagtail.blocks.StructBlock', [[('title', 15), ('subtitle', 16), ('primary_button_text', 17), ('primary_button_url', 5), ('secondary_button_text', 18), ('secondary_button_url', 5), ('background_style', 13)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 21: ('wagtail.blocks.RichTextBlock', (), {}), 22: ('wagtail.blocks.StructBlock', [[('title', 20), ('content', 21), ('background_style', 13)]], {}), 23: ('wagtail.blocks.ListBlock', (2,), {}), 24: ('wagtail.blocks.StructBlock', [[('title', 20), ('images', 23)]], {})}),
        ),
    ]
