# Generated by Django 5.2.6 on 2025-09-12 11:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_employeepage_hero_background_image_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepage',
            old_name='location',
            new_name='work_location',
        ),
        migrations.CreateModel(
            name='LocationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_hero', models.BooleanField(default=True, help_text='Show hero section at the top of this page')),
                ('hero_title', models.CharField(blank=True, default='Welcome to Beauty Salon', help_text='Main hero headline', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Transform your beauty with premium treatments', help_text='Subtitle text below the main headline')),
                ('hero_primary_button_text', models.CharField(blank=True, default='Book Now', help_text='Primary button text', max_length=50)),
                ('hero_primary_button_url', models.URLField(blank=True, help_text='Primary button URL')),
                ('hero_secondary_button_text', models.CharField(blank=True, default='Services', help_text='Secondary button text', max_length=50)),
                ('hero_secondary_button_url', models.URLField(blank=True, help_text='Secondary button URL')),
                ('location_name', models.CharField(help_text="Location name (e.g. 'Downtown Salon')", max_length=100)),
                ('address', models.TextField(help_text='Full address of this location')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Location description, amenities, special features')),
                ('monday_hours', models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='9:00 AM - 6:00 PM', max_length=50)),
                ('tuesday_hours', models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='9:00 AM - 6:00 PM', max_length=50)),
                ('wednesday_hours', models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='9:00 AM - 6:00 PM', max_length=50)),
                ('thursday_hours', models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='9:00 AM - 6:00 PM', max_length=50)),
                ('friday_hours', models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='9:00 AM - 6:00 PM', max_length=50)),
                ('saturday_hours', models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='10:00 AM - 4:00 PM', max_length=50)),
                ('sunday_hours', models.CharField(choices=[('Closed', 'Closed'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('8:00 AM - 5:00 PM', '8:00 AM - 5:00 PM'), ('8:00 AM - 6:00 PM', '8:00 AM - 6:00 PM'), ('8:00 AM - 8:00 PM', '8:00 AM - 8:00 PM'), ('9:00 AM - 5:00 PM', '9:00 AM - 5:00 PM'), ('9:00 AM - 6:00 PM', '9:00 AM - 6:00 PM'), ('9:00 AM - 7:00 PM', '9:00 AM - 7:00 PM'), ('9:00 AM - 8:00 PM', '9:00 AM - 8:00 PM'), ('10:00 AM - 4:00 PM', '10:00 AM - 4:00 PM'), ('10:00 AM - 5:00 PM', '10:00 AM - 5:00 PM'), ('10:00 AM - 6:00 PM', '10:00 AM - 6:00 PM'), ('11:00 AM - 4:00 PM', '11:00 AM - 4:00 PM'), ('11:00 AM - 5:00 PM', '11:00 AM - 5:00 PM')], default='Closed', max_length=50)),
                ('hero_background_image', models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero image (overlays background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('location_image', models.ForeignKey(blank=True, help_text='Location photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Location Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='LocationsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_hero', models.BooleanField(default=True, help_text='Show hero section at the top of this page')),
                ('hero_title', models.CharField(blank=True, default='Welcome to Beauty Salon', help_text='Main hero headline', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Transform your beauty with premium treatments', help_text='Subtitle text below the main headline')),
                ('hero_primary_button_text', models.CharField(blank=True, default='Book Now', help_text='Primary button text', max_length=50)),
                ('hero_primary_button_url', models.URLField(blank=True, help_text='Primary button URL')),
                ('hero_secondary_button_text', models.CharField(blank=True, default='Services', help_text='Secondary button text', max_length=50)),
                ('hero_secondary_button_url', models.URLField(blank=True, help_text='Secondary button URL')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the locations page')),
                ('hero_background_image', models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero image (overlays background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Locations Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
