# Generated by Django 5.2.6 on 2025-09-12 11:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_service_service_page_alter_service_description_and_more'),
        ('home', '0010_rename_location_employeepage_work_location_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_hero', models.BooleanField(default=True, help_text='Show hero section at the top of this page')),
                ('hero_title', models.CharField(blank=True, default='Welcome to Beauty Salon', help_text='Main hero headline', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Transform your beauty with premium treatments', help_text='Subtitle text below the main headline')),
                ('hero_primary_button_text', models.CharField(blank=True, default='Book Now', help_text='Primary button text', max_length=50)),
                ('hero_primary_button_url', models.URLField(blank=True, help_text='Primary button URL')),
                ('hero_secondary_button_text', models.CharField(blank=True, default='Services', help_text='Secondary button text', max_length=50)),
                ('hero_secondary_button_url', models.URLField(blank=True, help_text='Secondary button URL')),
                ('service_name', models.CharField(help_text="Service name (e.g. 'Haircut & Style')", max_length=100)),
                ('service_description', wagtail.fields.RichTextField(blank=True, help_text='Detailed description of the service')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in dollars (e.g. 45.00)', max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(help_text='How long does this service take? (in minutes)')),
                ('service_category', models.CharField(choices=[('hair', 'Hair Services'), ('nails', 'Nail Services'), ('skincare', 'Skincare & Facials'), ('massage', 'Massage & Spa'), ('makeup', 'Makeup Services'), ('other', 'Other Services')], default='other', help_text='Service category for organization', max_length=20)),
                ('available_locations', models.ManyToManyField(blank=True, help_text='Which locations offer this service?', to='booking.location')),
                ('hero_background_image', models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero image (overlays background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('service_image', models.ForeignKey(blank=True, help_text='Service photo or promotional image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Service Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_hero', models.BooleanField(default=True, help_text='Show hero section at the top of this page')),
                ('hero_title', models.CharField(blank=True, default='Welcome to Beauty Salon', help_text='Main hero headline', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Transform your beauty with premium treatments', help_text='Subtitle text below the main headline')),
                ('hero_primary_button_text', models.CharField(blank=True, default='Book Now', help_text='Primary button text', max_length=50)),
                ('hero_primary_button_url', models.URLField(blank=True, help_text='Primary button URL')),
                ('hero_secondary_button_text', models.CharField(blank=True, default='Services', help_text='Secondary button text', max_length=50)),
                ('hero_secondary_button_url', models.URLField(blank=True, help_text='Secondary button URL')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the services page')),
                ('hero_background_image', models.ForeignKey(blank=True, help_text='Background image for hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Hero image (overlays background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Services Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
