# Generated by Django 5.2.6 on 2025-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_servicepage_servicespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepage',
            name='work_location',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='available_locations',
        ),
        migrations.AddField(
            model_name='employeepage',
            name='work_location_name',
            field=models.CharField(blank=True, help_text="Employee's primary work location (e.g., 'Downtown Salon')", max_length=200),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='available_locations_text',
            field=models.TextField(blank=True, help_text="List of locations where this service is available (e.g., 'Downtown Salon, Westside Spa')"),
        ),
    ]
