# Generated by Django 5.2.6 on 2025-09-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_employeepage_work_location_and_more'),
    ]

    operations = [
    ]
