# Generated by Django 5.2.6 on 2025-09-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20250915_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepage',
            name='work_location_name',
        ),
        migrations.AddField(
            model_name='employeepage',
            name='work_location',
            field=models.ForeignKey(blank=True, help_text="Employee's primary work location", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='home.locationpage'),
        ),
    ]
