# Generated by Django 5.2.6 on 2025-09-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_employeepage_work_location_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='available_locations_text',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='available_locations',
            field=models.ManyToManyField(blank=True, help_text='Select which locations offer this service', related_name='available_services', to='home.locationpage'),
        ),
    ]
