# Generated by Django 5.2.6 on 2025-09-15 14:52

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_servicepage_available_locations_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='available_locations',
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('location', models.ForeignKey(help_text='Location where this service is available', on_delete=django.db.models.deletion.CASCADE, to='home.locationpage')),
                ('service', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to='home.servicepage')),
            ],
            options={
                'unique_together': {('service', 'location')},
            },
        ),
    ]
